### PR TITLE
First commit of HW1

### PR DESCRIPTION
**Pull request by nameistiffyp**
First commit!

### CODE REVIEW

**Comment by nameistiffyp** [comment]
Completed HW1 by creating 2 functions to start the game and compare numbers. Then created a loop to execute these functions up to five times.

**Comment by nameistiffyp** [comment]
Working on HW02_ch07_ex02; still trying to figure out how to stop function when input is "done"

**Comment by ProximaDas** [comment]
**D02_ex00**
Perfect.
One thing I would change to add a message when the program exits.

**HW02_ch07_ex02**
You're moving in the correct direction. Couple of things

- "while True" is not a good coding practice. while should always have a condition

- exit() is a python code - a strict no-no

- Try assigning "True" value to a global parameter before the while function, and update the parameter value once the condition is satisfied.

**Comment by nameistiffyp** [comment]
Hi Proxima,

You can access my solutions to HW4 here:
https://nbviewer.jupyter.org/gist/nameistiffyp/3891adf0d5400ca418a684b2ab3d0ad5

I had trouble finding an efficient way to compute find_five() in Ex3 and
the nested list() function.

Best,
Tiffany

**Pull request merged**
